# Build settings
markdown: kramdown

worknotes:
  theme: default
  colors: colors-rbw
  email: xiashuangxi@hotmail.com
  description: 个人的工作笔记。这里可以找到Java、Spring、Go或Python等相关的笔记。
  keywords: java,spring,go,python,ada,common lisp,面试,算法
  copyright: Copyright (C) 2020 · XIASHUANGXI@HOTMAIL.COM · All Rights Reserved. 